POST http://localhost:5000/api/v1/absen_tamu
Content-Type: application/json

{
    "fullname":"Hartanto",
    "institute":"university of nusa cendana",
    "email_address":"123@gmail.com"
}

###

PUT http://localhost:5000/api/v1/absen_peserta
Content-Type: application/json

{
  "participantId": "66c2f09172dea98a7013f382",
  "fullname": "Ringgo Agus Rahman, S.Pd, M.Cs"
}
